### ISSUE TITLE
new property like ...-inline or ...-block

### ISSUE THREAD

**Issue by 4dr1en** [twbs/stylelint-config-twbs-bootstrap#125]
It is Is it planned to add to this repos the `...-inline` and `...-block` properties since the support is quite good ?

ex : 
`margin-inline`
`padding-inline`
`border-inline`
`margin-block`
`padding-block`
`border-block`

**Comment by ffoodd** [comment]
Only in V6, since the support isn't good enough compared to our browser targets. It's been considered while implementing RTL support in v5 but logical properties weren't mature and supported enough ATM.

**Comment by XhmikosR** [comment]
We do seem to use `margin-inline-end` already, though in v5.

**Comment by ffoodd** [comment]
@XhmikosR We're not supposed to, or only as a progressive enhancement. Could you tell me where?

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/search?q=margin-inline-end

**Comment by ffoodd** [comment]
I think it's aligned with `::file-selector-button` support, which is only used as a progressive enhancement.

**Comment by 4dr1en** [comment]
thank you for your answer
