### ISSUE TITLE
Add CSS Grid properties support

### ISSUE THREAD

**Issue by roket1428** [twbs/stylelint-config-twbs-bootstrap#13]
Actually, what about things that are not in that repo? I mean like background-visibility? But mainly, css grid.

**Comment by MartijnCuppens** [comment]
We 're looking at updating our properties soon, so that they are also covered.

**Comment by roket1428** [comment]
> We 're looking at updating our properties soon, so that they are also covered.

Good to hear finally! Should I close the issue?

**Comment by MartijnCuppens** [comment]
Just leave it open until we fixed it so we can get the satisfaction of really saving the world by closing this issue with a PR 😉

**Comment by roket1428** [comment]
Okay then sir.

**Comment by roket1428** [comment]
I made this by myself. Do you think it is true? (The first 2 for where it should be I mean after the "display2 property.)

Here it is:
```json
    "box-sizing",
    "display",
    "grid",
    "grid-auto-flow",
    "grid-auto-rows",
    "grid-auto-columns",
    "grid-template",
    "grid-template-rows",
    "grid-template-columns",
    "grid-template-areas",
    "grid-gap",
    "grid-row-gap",
    "grid-column-gap",
    "grid-area",
    "grid-row",
    "grid-row-start",
    "grid-row-end",
    "grid-column",
    "grid-column-start",
    "grid-column-end",
    "place-content",
    "align-content",
    "justify-content",
    "place-items",
    "align-items",
    "justify-items",
    "place-self",
    "align-self",
    "justify-self",
```
