### ISSUE TITLE
`selector-class-pattern` change in >= v3.0.0-alpha1

### ISSUE THREAD

**Issue by danny007in** [twbs/stylelint-config-twbs-bootstrap#135]
Expected keyframe name to be kebab-case  keyframes-name-pattern
```css
@keyframes flipInX {
```

Expected class selector to be kebab-case  selector-class-pattern
```css
.svg-inline--fa,
```

**Comment by XhmikosR** [comment]
That intended. Feel free to disable the rule on your project.

**Comment by XhmikosR** [comment]
Actually, let's keep the issue open. I will rethink about it, but keep in mind this is a major version.

Either way the change was intentional, but if if people prefer the old way I guess we could revisit this change.

**Comment by XhmikosR** [comment]
@ffoodd do you think we should revert the `selector-class-pattern` change to our custom rule which was less restrictive? Now, it's strictly kebab case.

**Comment by ffoodd** [comment]
I'd be in favor of keeping it, as we only use kebab-case. Linter rules are meant to reinforce our coding conventions, so it totally makes sense this way.

**Comment by XhmikosR** [comment]
All right, I agree, but do note that we too had to override this in one case in our docs.

I'll release v3.0.0 tomorrow :)

**Comment by XhmikosR** [comment]
Closing since we are going to stick with the new behavior for the time being.
