### ISSUE TITLE
Consider disabling function-no-unknown for SCSS files

### ISSUE THREAD

**Issue by fgblomqvist** [twbs/stylelint-config-twbs-bootstrap#145]
It gives false-positives for regular SCSS functions like `lighten` or `map-get`.

**Comment by XhmikosR** [comment]
Where do you see this rule enabled exactly?

**Comment by fgblomqvist** [comment]
Oh my bad, it was turned on by the other config I extended 😅

**Comment by XhmikosR** [comment]
All good, I looked around and I couldn't see it enabled here :)
