### ISSUE TITLE
Update to Stylelint 15

### ISSUE THREAD

**Issue by tkrotoff** [twbs/stylelint-config-twbs-bootstrap#183]
https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md

**Comment by anthony0030** [comment]
I had this question as well. I was updating ```stylelint``` in a project I am working on and it came up with a warning about having an incorrect peer dependency. I see that ```stylelint-config-twbs-bootstrap@^7.0.0``` requires ```stylelint@14.14.0```.
Are there any plans to update to ```stylelint@15.0.0```?

**Comment by XhmikosR** [comment]
I released v8.0.0 with the updated dependencies but we need someone to go through our config and find replacements if any for the deprecated rules. See #188. If someone makes a PR please CC me.
