### ISSUE TITLE
Fix deprecation warnings/find replacements for these rules

### ISSUE THREAD

**Issue by XhmikosR** [twbs/stylelint-config-twbs-bootstrap#188]
- The "at-rule-semicolon-space-before" rule is deprecated.
 - The "at-rule-name-space-after" rule is deprecated.
 - The "block-closing-brace-empty-line-before" rule is deprecated.
 - The "block-closing-brace-newline-after" rule is deprecated.
 - The "block-opening-brace-space-before" rule is deprecated.
 - The "declaration-block-semicolon-newline-before" rule is deprecated.
 - The "max-empty-lines" rule is deprecated.
 - The "max-line-length" rule is deprecated.
 - The "number-leading-zero" rule is deprecated.
 - The "selector-list-comma-newline-before" rule is deprecated.
 - The "selector-list-comma-space-after" rule is deprecated.
 - The "selector-list-comma-space-before" rule is deprecated.
 - The "unicode-bom" rule is deprecated.
 - The "value-list-comma-newline-after" rule is deprecated.
 - The "value-list-comma-newline-before" rule is deprecated.
 - The "value-list-comma-space-after" rule is deprecated.

**Comment by owaisahmed5300** [comment]
Deprecation warnings:
 - The "at-rule-semicolon-space-before" rule is deprecated.
 - The "at-rule-name-space-after" rule is deprecated.
 - The "block-closing-brace-empty-line-before" rule is deprecated.
 - The "block-closing-brace-newline-after" rule is deprecated.
 - The "block-opening-brace-space-before" rule is deprecated.
 - The "declaration-block-semicolon-newline-before" rule is deprecated.
 - The "max-empty-lines" rule is deprecated.
 - The "max-line-length" rule is deprecated.
 - The "number-leading-zero" rule is deprecated.
 - The "selector-list-comma-newline-before" rule is deprecated.
 - The "selector-list-comma-space-after" rule is deprecated.
 - The "selector-list-comma-space-before" rule is deprecated.
 - The "unicode-bom" rule is deprecated.
 - The "value-list-comma-newline-after" rule is deprecated.
 - The "value-list-comma-newline-before" rule is deprecated.
 - The "value-list-comma-space-after" rule is deprecated.

**Comment by tagliala** [comment]
As far as I understand, these linters have been deprecated without replacement because it is supposed to be prettier's job to deal with those offences

https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md#deprecated-stylistic-rules

Does it mean that a new dependency is needed?

**Comment by XhmikosR** [comment]
I had a look at this and I can't figure out how to keep the previous stylelint options with prettier; it seems impossible :/

There's no replacement for these:

* `'number-leading-zero': 'never'`
* `'max-empty-lines': 2`
* allowing single line statements

**Comment by XhmikosR** [comment]
Branch: https://github.com/twbs/stylelint-config-twbs-bootstrap/compare/xmr/prettier

**Comment by XhmikosR** [comment]
I made #195 which should fixes all the issues. Thanks to @elirasza for making the package :)
