### ISSUE TITLE
stylelint output plagued by "DeprecationWarning: `context.fix` is being deprecated." (fixed on main)

### ISSUE THREAD

**Issue by tagliala** [twbs/stylelint-config-twbs-bootstrap#268]
Hello,

is it possible to release a new version of this package to allow new major versions of `@stylistic/stylelint-config` and `@stylistic/stylelint-plugin`?

This will avoid a noisy deprecation message introduced (by mistake) in stylelint 16.8.2: stylelint/stylelint#7895

Ref: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/10414818809/job/28844351365

**Comment by XhmikosR** [comment]
You can just update [@stylistic/stylelint-plugin](https://github.com/stylelint-stylistic/stylelint-stylistic) to v3.0.1 and the warnings will go away. The next version of our config needs to be probably a major one due to the major version bumps so I'm not sure when I'll get to cut a new version.

**Comment by XhmikosR** [comment]
Oh, wait, I missed the obvious. Our current release is using 2.x so you can't pick v3.x.

I'll try to cut a new major version in the next days, if not feel free to ping me.

**Comment by XhmikosR** [comment]
https://github.com/twbs/stylelint-config-twbs-bootstrap/releases/tag/v15.0.0

**Comment by tagliala** [comment]
Thanks for the prompt release, all warnings are gone
