### ISSUE TITLE
Drop IE properties

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/stylelint-config-twbs-bootstrap#51]
We can remove the IE properties in our config for v5. Not sure how we should handle versioning for v4 and v5 than though.

CC @XhmikosR

**Comment by XhmikosR** [comment]
Yeah, I think at this point, it's easier to just keep them. Otherwise we'll need to keep two branches in sync and a major version bump.

**Comment by stormwarning** [comment]
If I can humbly suggest, I maintain a property order config based on Recess/Bootstrap's order — https://github.com/stormwarning/stylelint-config-recess-order — updated to drop autoprefixable properties and add modern stuff like grid. Just putting it out there in case you find it easier to offload the property order stuff 👍

**Comment by chalkygames123** [comment]
@stormwarning BTW, how about adding it to https://github.com/stylelint/awesome-stylelint? (off-topic, sorry)

**Comment by XhmikosR** [comment]
Closing this since we have switched to https://github.com/stormwarning/stylelint-config-recess-order for quite some time now.
