### ISSUE TITLE
Rename repo/package

### ISSUE THREAD

**Issue by XhmikosR** [twbs/stylelint-config-twbs-bootstrap#6]
So, it seems there already was a stylelint-config-bootstrap npm package. My guess is it was passed over at some point to @mdo.

Now, we can't remove old npm releases, so v0.1.0 that exists there is not the same as ours. We could rename everything to `stylelint-config-twbs-bootstrap` maybe.

Let me know how you guys want to proceed.

/CC @mdo @MartijnCuppens

**Comment by MartijnCuppens** [comment]
Do we have access to remove the package? We can do that and than recreate the package and publish them with the correct versions?

**Comment by XhmikosR** [comment]
We can only deprecate it, not remove it.

**Comment by MartijnCuppens** [comment]
I guess `stylelint-config-twbs-bootstrap` is the only option then?

**Comment by XhmikosR** [comment]
I guess so too.

**Comment by XhmikosR** [comment]
Alternatively, I could just deprecate the old npm package and make a new one and keep the repo as is.

**Comment by XhmikosR** [comment]
To be honest it might be better to be consistent. We'll see.

**Comment by XhmikosR** [comment]
Package created and deprecated the old one

```
This package has been deprecated

Author message:
Please use `stylelint-config-twbs-bootstrap`
```

**Comment by XhmikosR** [comment]
Everything has been renamed.
