### ISSUE TITLE
Add `stylelint-high-performance-animation`

### ISSUE THREAD

**Issue by XhmikosR** [twbs/stylelint-config-twbs-bootstrap#8]
Maybe we should add https://github.com/kristerkari/stylelint-high-performance-animation?

Or do something like https://github.com/stylelint/stylelint/commit/072c1646a5c947a7b2e38a5d113ccae78da7cb49?

/CC @MartijnCuppens

**Comment by XhmikosR** [comment]
@twbs/css-review: thoughts about this?

**Comment by MartijnCuppens** [comment]
> Maybe we should add kristerkari/stylelint-high-performance-animation?

I'm ok with that.

> Or do something like stylelint/stylelint@072c164?

We use the transition mixin, so it's not really relevant for us.
