### ISSUE TITLE
Consider adding more rules

### ISSUE THREAD

**Issue by chalkygames123** [twbs/stylelint-config-twbs-bootstrap#86]
Hi,

I think we can make this config more strict by adding these rules:

- [function-calc-no-invalid](https://stylelint.io/user-guide/rules/function-calc-no-invalid#function-calc-no-invalid)
- [scss/at-each-key-value-single-line](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-each-key-value-single-line/README.md)
- [scss/at-if-no-null](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-if-no-null/README.md)
- [scss/at-rule-conditional-no-parentheses](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-rule-conditional-no-parentheses/README.md) (Autofixable)
- [scss/double-slash-comment-whitespace-inside](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/double-slash-comment-whitespace-inside/README.md)
- [scss/function-color-relative](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/function-color-relative/README.md)
- [scss/function-quote-no-quoted-strings-inside](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/function-quote-no-quoted-strings-inside/README.md) (Autofixable)
- [scss/function-unquote-no-unquoted-strings-inside](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/function-unquote-no-unquoted-strings-inside/README.md) (Autofixable)

Applying them to [Bootstrap](https://github.com/twbs/bootstrap) requires some manual fixes, but it's a simple task. The errors that will occur are:

```
$ npx stylelint "**/*.{css,scss}" --formatter verbose --fix

...

31 problems found
 severity level "error": 31
  scss/at-if-no-null: 11
  scss/function-color-relative: 18
  scss/dollar-variable-default: 1
  scss/double-slash-comment-whitespace-inside: 1
```

Note: `scss/dollar-variable-default` is irrelevant to this change.

I would be happy to send a PR if it's fine.

**Comment by XhmikosR** [comment]
> * [function-calc-no-invalid](https://stylelint.io/user-guide/rules/function-calc-no-invalid#function-calc-no-invalid)
> 
> * [scss/at-each-key-value-single-line](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-each-key-value-single-line/README.md)
> 
> * [scss/at-if-no-null](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-if-no-null/README.md)
> 
> * [scss/at-rule-conditional-no-parentheses](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-rule-conditional-no-parentheses/README.md) (Autofixable)
> 
> * [scss/double-slash-comment-whitespace-inside](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/double-slash-comment-whitespace-inside/README.md)
> 
> * [scss/function-color-relative](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/function-color-relative/README.md)
> 
> * [scss/function-quote-no-quoted-strings-inside](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/function-quote-no-quoted-strings-inside/README.md) (Autofixable)
> 
> * [scss/function-unquote-no-unquoted-strings-inside](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/function-unquote-no-unquoted-strings-inside/README.md) (Autofixable)

1. as long as it's not enabled by an inherited config, we could enable it
2. I'm personally not interested in one-liners
3. I guess it's OK
4. not sure I'd like this enabled either
5. I guess we could try but it's styling so it's subjective
6. Not sure about this either, last time I tried it I had some inconsistent results
7 and 8. are OK I guess

/CC @MartijnCuppens

**Comment by chalkygames123** [comment]
> as long as it's not enabled by an inherited config, we could enable it

Oops, sorry, `stylelint-config-recommended` already had it. https://github.com/stylelint/stylelint-config-recommended/blob/c4a22e40f01940ab5a0aac8757820f74c2841308/index.js#L18

**Comment by MartijnCuppens** [comment]
Agreeing with @XhmikosR here on the no-go's.

3. I prefer stricter checks for `null`
6. This only works for dart sass, not lib sass implementations
7. Not relevant for Bootstrap itself, because we use variables.
8. Same

Closing this.
