### ISSUE TITLE
Issues getting lint rules loaded

### ISSUE THREAD

**Issue by 0dp** [twbs/stylelint-config-twbs-bootstrap#9]
Hi there,

I've just stumbled across this project, and wanted to give it a spin.
In my postcss.config.js I've replaced `stylelint-config-standard` with `stylelint-config-twbs-bootstrap/scss` but am receiving a lot of linting warnings
```
// stylelint-config-twbs-bootstrap/scss
/src/style.scss 597 KiB {0} [built] [3624 warnings]
```
vs.
```
// stylelint-config-standard
./src/style.scss 597 KiB {0} [built] [4457 warnings]
```

For reference, my postcss.config.js
```
module.exports = () => ({
  plugins: {
    'stylelint': {
      "extends": "stylelint-config-twbs-bootstrap/scss",
    },
    'precss': {},
    'postcss-preset-env': {
      sourceMap: true,
    },
    'cssnano': {
      'autoprefixer': true
    }
  }
});
```
For reference, my style.scss
```
@import "~bootstrap/scss/bootstrap.scss";
```

**Comment by XhmikosR** [comment]
Can you share a repo showing the issue? We use this on the upstream repo ourselves and there are no errors.

**Comment by 0dp** [comment]
Sure thing. I will post it tomorrow

**Comment by 0dp** [comment]
https://github.com/0dp/stylelint-twbs-demo

**Comment by XhmikosR** [comment]
Hey, sorry for the late reply. From a quick look I can't `npm i` your test repo because I'm using Node.js 12.

@Johann-S: if you are still on Node.js 10, can you check the above test repo? I'm not even sure how's one supposed to make this work with postcss since I've never used stylelint this way myself.

**Comment by 0dp** [comment]
no worries. Not in a rush
